name: Release

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: taiki-e/install-action@just

      - uses: taiki-e/install-action@protoc

      - uses: bufbuild/buf-setup-action@v1.30.1
        with:
          version: 1.30.1
        name: Install Buf CLI

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Generate the library
        run: just generate

      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
